databases:
  - name: tiaojiao-db
    plan: free
    databaseName: questionnaire

services:
  - type: web
    name: tiaojiao
    env: node
    rootDir: backend
    buildCommand: npm install && cd ../frontend && npm install --include=dev && npm run build && cp -r dist ../backend/public
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: tiaojiao-db
          property: connectionString
